repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: file-contents-sorter
        files: requirements-dev.txt

# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v2.1.1
#     hooks:
#     -   id: seed-isort-config

# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: v4.3.21
#     hooks:
#     -   id: isort
#         additional_dependencies: [toml]
#         args: ['-m 3', '-tc' , '-w 160', '-sp .isort.cfg']

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.3'
    hooks:
    -   id: flake8
        additional_dependencies: ['pep8-naming']
        # Ignore all format-related checks as Black takes care of those.
        args: ['--ignore', 'E203, E231, E266, E501, W503, E731, E501, E731', '--select', 'B, C, E, F, W, N, T4', '--max-line-length=160', '--max-complexity=18']

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
