name: Linting and Testing
on:
  push:
    branches:
      - '*'
jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
    #   - name: Sort Imports
    #     run: |
    #       isort -rc superstructure --check --diff -sp .isort.cfg
      - name: Check black formatting
        run: |
          black . --check --diff

  test:
    runs-on: ubuntu-latest
    needs: linter
    strategy:
      matrix:
        python: ['3.7'] #, '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pytest --cov=superstructure tests/
          coveralls
